### ISSUE TITLE
The track method is inconsistent with the TypeScript typings.d.ts file

### ISSUE THREAD

**Issue by tokestermw** [launchdarkly/js-sdk-common#23]
**Is this a support request?**
No

**Describe the bug**

There are only two arguments in the `.track` method in the TypeScript file:
https://github.com/launchdarkly/js-sdk-common/blob/acf3e6a7b307cd0fecac4a4e74e1d1a58c12cd7b/typings.d.ts#L655

But three in the actual code:
https://github.com/launchdarkly/js-sdk-common/blob/9c506298bf0700b1fd85da3093fb93a96fd770be/src/index.js#L302

**To reproduce**
When using the JS SDK, I can't compile the code using TypeScript because of `Expected 1-2 arguments, but got 3.` error.

**Expected behavior**
Should have three arguments

**Logs**
N/A

**SDK version**
`"launchdarkly-react-client-sdk": "^2.18.0"`

**Language version, developer tools**
Python, Node, React

**OS/platform**
Mac OS 10.15

**Additional context**
N/A

**Comment by eli-darkly** [comment]
Sorry about this - it was just brought to our attention earlier today and we'll have a patch out ASAP.

**Comment by eli-darkly** [comment]
Note that the 3.2.8 release isn't something you should update separately - we will have a `launchdarkly-js-client-sdk` release out shortly that includes the fix.

**Comment by eli-darkly** [comment]
OK, [version 2.17.5](https://github.com/launchdarkly/js-client-sdk/releases/tag/2.17.5) of the JS SDK has been released with the fix for this.
