### ISSUE TITLE
Mistake in type docs about omit user key

### ISSUE THREAD

**Issue by timwangdev** [launchdarkly/js-sdk-common#59]
https://github.com/launchdarkly/js-sdk-common/blob/05a82f9ce4b665eb572dd8093567329a717172d7/typings.d.ts#L266-L280

Hi, I found this line of description was not very clear. It says `If you omit this property, and also set anonymous to true` it should work, and `It is an error to omit the key property if anonymous is not set.`.

However, if you omit the `key` or set the `key` to `null` or `undefined`, it would always return an error, no matter the `anonymous` is set or not.

I don't know what is the expected behavior here.

**Comment by eli-darkly** [comment]
> However, if you omit the key or set the key to null or undefined, it would always return an error, no matter the anonymous is set or not

Are you saying that that is what you are actually seeing in practice? Like, you have tried omitting the key and setting `anonymous` to true, and the SDK did _not_ generate a UUID key but instead threw an error? It is supposed to do so; if it isn't, that's a bug, not a documentation mistake.

Also, if so, it would be helpful to know which SDK (and which version) you are using. This repo is common code that is used by several SDKs.

**Comment by timwangdev** [comment]
Hi @eli-darkly, I've tried omitting the key and setting `anonymous` to true, the API still returns an error. And I've checked the request the decoded base64 JSON `key` is missing.

But, I've checked the SDK we used, it's an older version `ldclient-js` which may not support this. This issue may not be relevant to the newer SDK version. Sorry about that and it's ok to close this issue.

**Comment by eli-darkly** [comment]
@timwangdev Auto-generation of a key has been supported since v2.10.0. If you're using a version earlier than that, then that would explain it. If not, then in order to investigate this we would need more information such as 1. what version are you using, 2. example code of how you're initializing the SDK, 3. what is the error.

**Comment by timwangdev** [comment]
@eli-darkly we are using the version `ldclient-js: 2.4.0`. I'll try to update it to a newer version to see if it works.
Basically we are using a system-generated id, for user keys, but sometimes the id was not reliable (eg. for new accounts), passing null value would have initialization error reports from LD API and the user could not get the FFs. We expect LD could still work in the `anonymous` mode.

**Comment by timwangdev** [comment]
Hi @eli-darkly , sorry for the late update. We migrate our code from an internal wrapper to the latest `launchdarkly-js-client-sdk` and the `anonymous` mode without user key works fine. I'm closing this issue now, thanks!
