### ISSUE TITLE
LDContext type is incorrect and errors when accessing `kind` property

### ISSUE THREAD

**Issue by johnnywang** [launchdarkly/js-sdk-common#94]
**Describe the bug**
If you have a variable of type `LDContext` and try to check/access the `kind` property, TS will error out at you saying that `Property 'kind' does not exist on type 'LDUser'.`

**To reproduce**
Trivial, but something like this should trigger the TS error:

```
const c: LDContext;
const test = c.kind === 'user';
```

**Expected behavior**
Accessing `kind` should not throw a TS error

**SDK version**
"launchdarkly-react-native-client-sdk": "^7.1.5"

**Language version, developer tools**
React Native

**OS/platform**
MacOS

**Additional context**
LDUser should probably extend LDSingleKindContext

**Comment by louis-launchdarkly** [comment]
Hello @johnnywang, thank you for reporting the issue. We will look into this and follow up once we investigated this.

Filed internally as _210517_.

**Comment by yusinto** [comment]
Hi @johnnywang, LDContext is a new concept in LaunchDarkly which is an evolution of the legacy LDUser type.

An LDContext can be a single-kind, a multi-kind or a legacy LDUser.

For backward compatibility for now, we allow using LDUser anywhere we accept a LDContext. The absence of kind is used to know that it is an LDUser. If you are only using LDSingleKindContexts or LDMultiKindContexts, then please use those types instead.

We are planning to deprecate and remove LDUser in the future.

**Comment by johnnywang** [comment]
Hey @yusinto! Did you try the repro example above? This TS error happens because there's the `LDUser` is present on the `LDContext` union type, and because it's missing the `kind` field, so even if we're NOT using the deprecated `LDUser`, it'll still throw that error since it's a possible type in the union

**Comment by yusinto** [comment]
Hi @johnnywang currently, the `LDUser` is in the union type for backward compatibility reasons. The `LDUser` will be removed in the future and by then the `kind` property will be directly accessible via the union type.

In the meantime, to check for context kind, you can do the [following](https://github.com/launchdarkly/react-client-sdk/blob/780a07ede06189580651daf4362821417cf6ce51/examples/typescript/src/App.tsx#L11):

```tsx
function App() {
  const ldClient = useLDClient();
  const context = ldClient?.getContext();

  // detecting context kind
  if (context && 'kind' in context) {
    if (context.kind === 'multi') {
      console.log(`=== multi context`);
    } else {
      console.log(`=== single context: ${context.kind}`);
    }
  } else {
    console.log('=== Legacy LDUser');
  }
```
