### ISSUE TITLE
`events.slice` is not a function

### ISSUE THREAD

**Issue by dvargas92495** [launchdarkly/js-sdk-common#96]
**Describe the bug**
Intermittently, I'm seeing [this line](https://github.com/launchdarkly/js-sdk-common/blob/main/src/utils.js#L124) throw a type error bc `events` is not an array, both in the browser and during `jest` testing.

**To reproduce**
I could try to post a minimal reproducible repo if it would help, but I think I see what's going wrong in the code itself:
- `chunkEventsForUrl` is expecting `events` to be an array
- it's called by `EventSender.sendEvents` [here](https://github.com/launchdarkly/js-sdk-common/blob/main/src/EventSender.js#L76) which is also expecting `events` to be an array.
- However, that's called by `sendDiagnosticEvent` [here](https://github.com/launchdarkly/js-sdk-common/blob/main/src/diagnosticEvents.js#L104-L105), which is passing in only a _single_ event to the whole flow, which then triggers the `events.slice` is not a function error. I believe the argument here should be `[event]` - it's not clear to me what's sending the diagnostic event based on the traceback.

My use case is a bit involved so it would take time to narrow down to a minimal reproducible example, especially since the error triggers non-deterministically. However, I believe the code fix here appears to be straightforward enough without one.

**Expected behavior**
Launch Darkly sdk to run without erroring

**Logs**
![Screenshot 2023-10-10 at 11 57 55 AM](https://github.com/launchdarkly/js-sdk-common/assets/7143571/e40a84a1-65a5-43bc-9256-a102633f7c65)

**SDK version**
└─┬ launchdarkly-react-client-sdk@3.0.4
  └─┬ launchdarkly-js-client-sdk@3.1.2
    └── launchdarkly-js-sdk-common@5.0.3

**Language version, developer tools**
npm -v
8.19.3
node -v
v16.19.0

**OS/platform**
Mac M1 Apple Silicon

**Additional context**
_N/A_

**Comment by kinyoklion** [comment]
Hello @dvargas92495,

I agree that this is a bug, but generally speaking should not be happening (or at least not often) for real users. We will be releasing some new SDKs soon that do not contain this functionality.

The reason it generally should not be happening is that we should not be chunking events for platforms that support post. Being as browsers for some time have effectively universally supported post, this likely was missed during testing, with diagnostic events being added at a point where the lack of post support was uncommon.

 I am concerned though that possibly POST support detection is not working correctly in some situation. Do you have any meta-data for browsers that have been encountering this error?

Thank you,
Ryan

**Comment by dvargas92495** [comment]
> is that we should not be chunking events for platforms that support post.

By this do you mean HTTP `POST` requests, `window.postMessage` API, or some other third concept?

We are mainly hitting this during our `jest` unit testing, where we mock HTTP requests instead of the `useFlags()` hook. If you could point me in the direction of what it's checking for "supporting post" then we could likely improve our test dom environment to cover that and resolve this issue. Otherwise, we'll likely fallback to mocking `useFlags()` hook

**Comment by kinyoklion** [comment]
@dvargas92495 HTTP POST support. The detection code for the js-client-sdk is here: https://github.com/launchdarkly/js-client-sdk/blob/8675ab6b0d1a4833e4e140af3658011bf48b2162/src/browserPlatform.js#L24

Technically it is support for CORS, but effectively we wouldn't be able to use HTTP POST from a browser without CORS support. When CORS isn't supported a workaround using HTTP GET is done.

**Comment by dvargas92495** [comment]
ah ok I think that gives me what I need - thank you!
